/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package finalproject;

import java.awt.Color;
import javax.swing.BorderFactory;
import javax.swing.table.JTableHeader;

/**
 *
 * @author acer
 */
public class ProjectGUI extends javax.swing.JFrame {

    /**
     * Creates new form ProjectGUI
     */
    public ProjectGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGroupSpiciness = new javax.swing.ButtonGroup();
        btnSearch = new javax.swing.JButton();
        panelBG = new javax.swing.JPanel();
        fileMenuOpen = new javax.swing.JPanel();
        menuItem1 = new javax.swing.JLabel();
        menuItem2 = new javax.swing.JLabel();
        panelMenu = new javax.swing.JPanel();
        menuHelp = new javax.swing.JLabel();
        menuFile = new javax.swing.JLabel();
        txtSearch = new javax.swing.JTextField();
        logoImg = new javax.swing.JLabel();
        searchBtnPanel = new javax.swing.JPanel();
        searchButton = new javax.swing.JButton();
        panelSideBar = new javax.swing.JPanel();
        lblAddMenu = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        txtDishNo = new javax.swing.JTextField();
        lblDishNo = new javax.swing.JLabel();
        txtDishName = new javax.swing.JTextField();
        lblDishName = new javax.swing.JLabel();
        lblDishCategory = new javax.swing.JLabel();
        rbHot = new javax.swing.JRadioButton();
        rbMild = new javax.swing.JRadioButton();
        rbCold = new javax.swing.JRadioButton();
        lblSpiciness = new javax.swing.JLabel();
        btnInsert = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        lbCheckItems = new javax.swing.JLabel();
        lblI = new javax.swing.JLabel();
        cbDishCategory = new javax.swing.JComboBox<>();
        cbDishCategorySearch = new javax.swing.JComboBox<>();
        btnCount = new javax.swing.JButton();
        panelContent = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblListingTable = new javax.swing.JTable();
        btnClearAll = new javax.swing.JButton();
        btnClearSelected = new javax.swing.JButton();

        btnSearch.setIcon(new javax.swing.ImageIcon("F:\\College\\Emerging Programming Platforms and Technologies\\Course Work I\\design\\search.png")); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelBG.setBackground(new java.awt.Color(241, 241, 241));
        panelBG.setLayout(null);

        fileMenuOpen.setBackground(new java.awt.Color(255, 0, 0));
        fileMenuOpen.setAlignmentX(20.0F);
        fileMenuOpen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                fileMenuOpenMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                fileMenuOpenMouseExited(evt);
            }
        });

        menuItem1.setBackground(new java.awt.Color(25, 2, 32));
        menuItem1.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        menuItem1.setForeground(new java.awt.Color(255, 255, 255));
        menuItem1.setText("Open");
        menuItem1.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        menuItem1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menuItem1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                menuItem1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                menuItem1MouseExited(evt);
            }
        });

        menuItem2.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        menuItem2.setForeground(new java.awt.Color(255, 255, 255));
        menuItem2.setText("Exit");
        menuItem2.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        menuItem2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menuItem2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                menuItem2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                menuItem2MouseExited(evt);
            }
        });

        javax.swing.GroupLayout fileMenuOpenLayout = new javax.swing.GroupLayout(fileMenuOpen);
        fileMenuOpen.setLayout(fileMenuOpenLayout);
        fileMenuOpenLayout.setHorizontalGroup(
            fileMenuOpenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fileMenuOpenLayout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addGroup(fileMenuOpenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(menuItem2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(menuItem1, javax.swing.GroupLayout.DEFAULT_SIZE, 196, Short.MAX_VALUE))
                .addGap(2, 2, 2))
        );
        fileMenuOpenLayout.setVerticalGroup(
            fileMenuOpenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fileMenuOpenLayout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addComponent(menuItem1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(menuItem2)
                .addGap(0, 0, 0))
        );

        fileMenuOpen.setVisible(false);

        panelBG.add(fileMenuOpen);
        fileMenuOpen.setBounds(82, 70, 200, 110);

        panelMenu.setBackground(new java.awt.Color(172, 0, 76));

        menuHelp.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        menuHelp.setForeground(new java.awt.Color(255, 255, 255));
        menuHelp.setText("Help");
        menuHelp.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        menuHelp.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menuHelp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                menuHelpMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                menuHelpMouseExited(evt);
            }
        });

        menuFile.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        menuFile.setForeground(new java.awt.Color(255, 255, 255));
        menuFile.setText("File");
        menuFile.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        menuFile.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menuFile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                menuFileMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                menuFileMouseExited(evt);
            }
        });

        txtSearch.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtSearch.setForeground(new java.awt.Color(153, 153, 153));
        txtSearch.setText("Search Item");
        txtSearch.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        txtSearch.setMargin(new java.awt.Insets(10, 2, 10, 2));
        txtSearch.setPreferredSize(new java.awt.Dimension(80, 18));
        txtSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearchActionPerformed(evt);
            }
        });

        logoImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/finalproject/logo_icon.png"))); // NOI18N

        searchBtnPanel.setBackground(new java.awt.Color(148, 3, 58));
        searchBtnPanel.setPreferredSize(new java.awt.Dimension(40, 40));

        searchButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/finalproject/search.png"))); // NOI18N
        searchButton.setAlignmentX(3.0F);
        searchButton.setAlignmentY(3.0F);
        searchButton.setPreferredSize(new java.awt.Dimension(34, 34));
        searchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtonActionPerformed(evt);
            }
        });
        searchBtnPanel.add(searchButton);
        searchButton.setOpaque(false);
        searchButton.setContentAreaFilled(false);
        searchButton.setBorderPainted(false);

        javax.swing.GroupLayout panelMenuLayout = new javax.swing.GroupLayout(panelMenu);
        panelMenu.setLayout(panelMenuLayout);
        panelMenuLayout.setHorizontalGroup(
            panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMenuLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(logoImg)
                .addGap(29, 29, 29)
                .addComponent(menuFile, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(menuHelp, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 630, Short.MAX_VALUE)
                .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(searchBtnPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(81, 81, 81))
        );
        panelMenuLayout.setVerticalGroup(
            panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMenuLayout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(searchBtnPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE)
                    .addComponent(txtSearch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(13, 13, 13))
            .addComponent(menuFile, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(menuHelp, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(logoImg, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        panelBG.add(panelMenu);
        panelMenu.setBounds(0, 0, 1190, 70);

        panelSideBar.setBackground(new java.awt.Color(199, 0, 76));

        lblAddMenu.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        lblAddMenu.setForeground(new java.awt.Color(255, 255, 255));
        lblAddMenu.setText("Add Records");

        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));

        lblDishNo.setForeground(new java.awt.Color(255, 255, 255));
        lblDishNo.setText("Dish Number");

        txtDishName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDishNameActionPerformed(evt);
            }
        });

        lblDishName.setForeground(new java.awt.Color(255, 255, 255));
        lblDishName.setText("Dish Name");

        lblDishCategory.setForeground(new java.awt.Color(255, 255, 255));
        lblDishCategory.setText("Dish Category");

        rbHot.setForeground(new java.awt.Color(255, 255, 255));
        rbHot.setText("Hot");
        rbHot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbHotActionPerformed(evt);
            }
        });

        rbMild.setForeground(new java.awt.Color(255, 255, 255));
        rbMild.setText("Mild");
        rbMild.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbMildActionPerformed(evt);
            }
        });

        rbCold.setForeground(new java.awt.Color(255, 255, 255));
        rbCold.setText("Cold");
        rbCold.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbColdActionPerformed(evt);
            }
        });

        lblSpiciness.setForeground(new java.awt.Color(255, 255, 255));
        lblSpiciness.setText("Spiciness");

        btnInsert.setText("Insert");

        btnClear.setText("Clear");

        jSeparator2.setForeground(new java.awt.Color(255, 255, 255));

        lbCheckItems.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        lbCheckItems.setForeground(new java.awt.Color(255, 255, 255));
        lbCheckItems.setText("Check Items in Category");

        lblI.setForeground(new java.awt.Color(255, 255, 255));
        lblI.setText("Dish Category");

        cbDishCategory.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Lamb", "Beef", "Chicken", "Pork" }));
        cbDishCategory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbDishCategoryActionPerformed(evt);
            }
        });

        cbDishCategorySearch.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Lamb", "Beef", "Chicken", "Pork" }));
        cbDishCategorySearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbDishCategorySearchActionPerformed(evt);
            }
        });

        btnCount.setText("Count Items");

        javax.swing.GroupLayout panelSideBarLayout = new javax.swing.GroupLayout(panelSideBar);
        panelSideBar.setLayout(panelSideBarLayout);
        panelSideBarLayout.setHorizontalGroup(
            panelSideBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSideBarLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(panelSideBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cbDishCategory, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblI)
                    .addComponent(lbCheckItems, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblSpiciness)
                    .addGroup(panelSideBarLayout.createSequentialGroup()
                        .addComponent(rbHot)
                        .addGap(18, 18, 18)
                        .addComponent(rbMild)
                        .addGap(18, 18, 18)
                        .addComponent(rbCold))
                    .addComponent(lblDishNo)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelSideBarLayout.createSequentialGroup()
                        .addComponent(btnInsert, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelSideBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(panelSideBarLayout.createSequentialGroup()
                            .addComponent(lblDishCategory)
                            .addGap(145, 145, 145))
                        .addGroup(panelSideBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtDishNo)
                            .addComponent(jSeparator1)
                            .addComponent(lblAddMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblDishName)
                            .addComponent(txtDishName, javax.swing.GroupLayout.DEFAULT_SIZE, 224, Short.MAX_VALUE)))
                    .addComponent(jSeparator2)
                    .addComponent(cbDishCategorySearch, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCount, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        panelSideBarLayout.setVerticalGroup(
            panelSideBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSideBarLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(lblAddMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblDishNo)
                .addGap(0, 0, 0)
                .addComponent(txtDishNo, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblDishName)
                .addGap(0, 0, 0)
                .addComponent(txtDishName, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblDishCategory)
                .addGap(0, 0, 0)
                .addComponent(cbDishCategory, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addComponent(lblSpiciness)
                .addGap(0, 0, 0)
                .addGroup(panelSideBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbHot)
                    .addComponent(rbMild)
                    .addComponent(rbCold))
                .addGap(18, 18, 18)
                .addGroup(panelSideBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnInsert, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(lbCheckItems, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblI)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbDishCategorySearch, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnCount, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(139, Short.MAX_VALUE))
        );

        panelBG.add(panelSideBar);
        panelSideBar.setBounds(0, 66, 274, 750);

        panelContent.setBackground(new java.awt.Color(241, 241, 241));

        tblListingTable.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        tblListingTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Dish No.", "Dish Name", "Category", "Spiciness", "Price"
            }
        ));
        JTableHeader tHeader = tblListingTable.getTableHeader();
        tHeader.setBackground(Color.MAGENTA);
        jScrollPane1.setViewportView(tblListingTable);

        btnClearAll.setText("Clear All");

        btnClearSelected.setText("Clear Selected");

        javax.swing.GroupLayout panelContentLayout = new javax.swing.GroupLayout(panelContent);
        panelContent.setLayout(panelContentLayout);
        panelContentLayout.setHorizontalGroup(
            panelContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelContentLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 911, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnClearSelected, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnClearAll, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelContentLayout.setVerticalGroup(
            panelContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelContentLayout.createSequentialGroup()
                .addGap(159, 159, 159)
                .addGroup(panelContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnClearAll, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnClearSelected, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(panelContentLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 596, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        panelBG.add(panelContent);
        panelContent.setBounds(274, 66, 1257, 596);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelBG, javax.swing.GroupLayout.DEFAULT_SIZE, 1185, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelBG, javax.swing.GroupLayout.DEFAULT_SIZE, 816, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSearchActionPerformed

    private void rbHotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbHotActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbHotActionPerformed

    private void rbMildActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbMildActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbMildActionPerformed

    private void rbColdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbColdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbColdActionPerformed

    private void txtDishNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDishNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDishNameActionPerformed

    private void cbDishCategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbDishCategoryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbDishCategoryActionPerformed

    private void cbDishCategorySearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbDishCategorySearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbDishCategorySearchActionPerformed

    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchButtonActionPerformed

    private void menuFileMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuFileMouseEntered
        // TODO add your handling code here:
        fileMenuOpen.setVisible(true);
        menuFile.setOpaque(true);
        menuFile.setBackground(Color.RED);
    }//GEN-LAST:event_menuFileMouseEntered

    private void menuFileMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuFileMouseExited
        // TODO add your handling code here:
        fileMenuOpen.setVisible(false);
        fileMenuOpen.repaint();
        menuFile.setBackground(null);
        menuFile.setOpaque(false);
    }//GEN-LAST:event_menuFileMouseExited

    private void fileMenuOpenMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fileMenuOpenMouseEntered
        // TODO add your handling code here:
        fileMenuOpen.setVisible(true);
    }//GEN-LAST:event_fileMenuOpenMouseEntered

    private void fileMenuOpenMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fileMenuOpenMouseExited
        // TODO add your handling code here:
        fileMenuOpen.setVisible(false);
        
    }//GEN-LAST:event_fileMenuOpenMouseExited

    private void menuItem1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuItem1MouseEntered
        // TODO add your handling code here:
        fileMenuOpen.setVisible(true);
        menuItem1.setOpaque(true);
        menuItem1.setBackground(new java.awt.Color(172,0,76));
    }//GEN-LAST:event_menuItem1MouseEntered

    private void menuItem1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuItem1MouseExited
        // TODO add your handling code here:
        menuItem1.setBackground(null);
        menuItem1.setOpaque(false);
        fileMenuOpen.setVisible(false);
    }//GEN-LAST:event_menuItem1MouseExited

    private void menuItem2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuItem2MouseEntered
        // TODO add your handling code here:
        fileMenuOpen.setVisible(true);
        menuItem2.setOpaque(true);
        menuItem2.setBackground(new java.awt.Color(172,0,76));
    }//GEN-LAST:event_menuItem2MouseEntered

    private void menuItem2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuItem2MouseExited
        // TODO add your handling code here:
        menuItem1.setBackground(null);
        menuItem2.setOpaque(false);
        fileMenuOpen.setVisible(false);
    }//GEN-LAST:event_menuItem2MouseExited

    private void menuHelpMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuHelpMouseEntered
        // TODO add your handling code here:
        menuHelp.setOpaque(true);
        menuHelp.setBackground(Color.RED);
    }//GEN-LAST:event_menuHelpMouseEntered

    private void menuHelpMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuHelpMouseExited
        // TODO add your handling code here:
        menuHelp.setBackground(null);
        menuHelp.setOpaque(false);
    }//GEN-LAST:event_menuHelpMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProjectGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProjectGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProjectGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProjectGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProjectGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnClearAll;
    private javax.swing.JButton btnClearSelected;
    private javax.swing.JButton btnCount;
    private javax.swing.ButtonGroup btnGroupSpiciness;
    private javax.swing.JButton btnInsert;
    private javax.swing.JButton btnSearch;
    private javax.swing.JComboBox<String> cbDishCategory;
    private javax.swing.JComboBox<String> cbDishCategorySearch;
    private javax.swing.JPanel fileMenuOpen;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lbCheckItems;
    private javax.swing.JLabel lblAddMenu;
    private javax.swing.JLabel lblDishCategory;
    private javax.swing.JLabel lblDishName;
    private javax.swing.JLabel lblDishNo;
    private javax.swing.JLabel lblI;
    private javax.swing.JLabel lblSpiciness;
    private javax.swing.JLabel logoImg;
    private javax.swing.JLabel menuFile;
    private javax.swing.JLabel menuHelp;
    private javax.swing.JLabel menuItem1;
    private javax.swing.JLabel menuItem2;
    private javax.swing.JPanel panelBG;
    private javax.swing.JPanel panelContent;
    private javax.swing.JPanel panelMenu;
    private javax.swing.JPanel panelSideBar;
    private javax.swing.JRadioButton rbCold;
    private javax.swing.JRadioButton rbHot;
    private javax.swing.JRadioButton rbMild;
    private javax.swing.JPanel searchBtnPanel;
    private javax.swing.JButton searchButton;
    private javax.swing.JTable tblListingTable;
    private javax.swing.JTextField txtDishName;
    private javax.swing.JTextField txtDishNo;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables
}
